### ISSUE TITLE
plugin does not seem to work on neovim

### ISSUE THREAD

**Issue by assaf758** [mzlogin/vim-markdown-toc#16]
after successful install of plugin, command :GenTocGFM  does not exist

**Comment by mzlogin** [comment]
I don't use neovim, so I don't know if this plugin can works fine in it.

Can you feedback me the following commands' output?

1. `:set filetype`

    vim-markdown-toc only works in Markdown files.

2. `:echo g:loaded_MarkdownTocPlugin`

    To check if vim-markdown-toc loaded successfully.

**Comment by mzlogin** [comment]
I install a neovim in my Windows 10 just now, it seems vim-markdown-toc can work file on it.

![neovim](https://cloud.githubusercontent.com/assets/1646590/19891447/2c8f214c-a07b-11e6-9761-471aca56aa00.gif)

**Comment by assaf758** [comment]
in my case (running ubuntu) I'm not getting anything for this
:echo g:loaded_MarkdownTocPlugin

**Comment by mzlogin** [comment]
So this plugin does not loaded.

What you get from `:set filetype`?

If the output is `markdown`, then you should fix the plugin installation.

And if the output is not `markdown`, try `:set filetype=markdown` and then run `:GenTocGFM` again, if it works, the plugin is installed successfully, but the filetype does not set correct. Otherwise, check the plugin installation.

**Comment by assaf758** [comment]
not sure what I did, but it works now.

**Comment by mzlogin** [comment]
OK, glad to hear that whatever.
